---
title: "Contribution au défi 4k - Olivier Querry"
format: 
  dashboard:
    orientation: columns
---

```{r setup}
source("R/script.R")
```

# Dashboard

## Icons 1 {width="35%"}
```{r don}
#| content: valuebox
#| title: "Don de bidoux"
list(
  icon = "coin",
  color = "#daa520",
  value = paste0(n, "$")
)
```

```{r nombre}
#| content: valuebox
#| title: "Nombre total de sortie"
list(
  icon = "check2-circle",
  color = "primary",
  value = n
)
```

```{r average}
#| content: valuebox
#| title: "Nombre de sortie par semaine"
list(
  icon = "calendar2-week-fill",
  color = "info",
  value = round(weekly_average, 1)
)
```


## Icons 2 {width="35%"}
```{r rate}
#| content: valuebox
#| title: "Si la tendance ce maintien"
list(
  icon = "bar-chart-line-fill",
  color = "light",
  value = paste0(round(weekly_average, 1) * 53, "$")
)

```

```{r km}
#| content: valuebox
#| title: "Nombre total de kilomètre"
list(
  icon = "signpost-split",
  color = "light",
  value = paste(round(km, 1), "km")
)
```

```{r elevation}
#| content: valuebox
#| title: "Nombre total d'élévation"
list(
  icon = "chevron-double-up",
  color = "light",
  value = paste(round(elevation$up, 1), "m")
)
```


## Figure {width="30%"}

```{r}
#| fig-height: 5
#| fig-width: 3
fig
```


# Trajets

```{r route heatmap}
heatmap
```

```{r route table}
as_tibble(all) %>% select(-5) %>% 
  mutate(
    km = round(km, 1),
    up = round(up),
    down = round(down)
    ) %>% 
  DT::datatable()
```
